server:
  port: 8000

spring:
  cloud:
    discovery:
          locator:
            enabled: true
    gateway:
      routes:
        - id: ola-service
          uri: lb://JOAO_RAMOS_TP1_OLASERVICE
          predicates:
            - Path=/app/**, /app

        - id: frontEnd
          uri: lb://JOAO_RAMOS_TP1_FRONTEND
          predicates:
            - Path=/api/**

        - id: admin
          uri: http://localhost:8761
          predicates:
            - Path=/admin/**, /admin