server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: lb://JOAO_RAMOS_TP1_OLASERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/app/**

        - id: FrontEnd
          uri: lb://JOAO_RAMOS_TP1_FRONTEND
          predicates:
            - Path=/api/**

        - id: Admin
          uri: http://localhost:8761
          predicates:
            - Path=/admin/**