server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: OlaService
          uri: http://localhost:8082
          predicates:
            - Path=/app/**

        - id: FrontEnd
          uri: http://localhost:8081
          predicates:
            - Path=/api/**

        - id: Admin
          uri: http://localhost:8761
          predicates:
            - Path=/admin/**