spring:
  config:
    import: constants.yaml

  cloud:
    gateway:
      enabled: true
      default-filters:
        - StripPrefix=1 
      routes:
        - id: ola-service
          uri: ${OlaService.service_url}
          predicates:
            - Path=${OlaService.gateway_path},${OlaService.gateway_path}/**
          filters:
            - RewritePath=${OlaService.gateway_path}(?<segment>.*), /$\{segment}

        - id: frontend
          uri: ${Frontend.service_url}
          predicates:
            - Path=${Frontend.gateway_path},${Frontend.gateway_path}/**,/,/error,/error/**,/appcss/**,/appjs/**,/appimages/**
          filters:
            - RewritePath=${Frontend.gateway_path}(?<segment>.*), /$\{segment}
            
        - id: admin
          uri: ${Admin.service_url}
          predicates:
            - Path=${Admin.gateway_path},${Admin.gateway_path}/**,/eureka/**,/eureka
          filters:
            - RewritePath=${Admin.gateway_path}(?<segment>.*), /$\{segment}



server:
  port: ${ApiGateway.port}


management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: ${Admin.service_url}/eureka/
